namespace SinBordes;

/// <summary>
/// Textos de la UI por idioma. Sin recursos .resx ni dependencias: un diccionario por
/// idioma y fallback a inglés si falta una clave. El idioma vive en config.json.
/// </summary>
public static class Textos
{
    public static string Idioma = "en";

    public static readonly (string Codigo, string Nombre)[] Disponibles =
    {
        ("en", "English"),
        ("es", "Español"),
        ("pt", "Português (Brasil)"),
        ("fr", "Français"),
        ("de", "Deutsch"),
        ("ru", "Русский"),
    };

    public static string T(string clave) =>
        Tablas.TryGetValue(Idioma, out var tabla) && tabla.TryGetValue(clave, out var texto) ? texto
        : Tablas["en"].TryGetValue(clave, out var ingles) ? ingles
        : clave;

    public static string F(string clave, params object[] args) => string.Format(T(clave), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tablas = new()
    {
        ["en"] = new()
        {
            ["boton.aplicar"] = "Make borderless",
            ["boton.deshacer"] = "Undo",
            ["boton.guardar"] = "Add to library",
            ["boton.quitar"] = "Remove from library",
            ["boton.actualizar"] = "Refresh",
            ["boton.ajustes"] = "Settings…",
            ["menu.colores"] = "Colors",
            ["menu.fondo"] = "Background…",
            ["menu.panel"] = "Buttons and bars…",
            ["menu.acento"] = "Accent…",
            ["menu.texto"] = "Text…",
            ["menu.restablecer"] = "Reset",
            ["menu.esquinas"] = "Rounded corners",
            ["menu.autoarranque"] = "Start with Windows",
            ["menu.arrancarMin"] = "Start minimized to tray",
            ["menu.cerrarMin"] = "Close button minimizes to tray",
            ["menu.altintro"] = "Send Alt+Enter to selection",
            ["menu.hotkey"] = "Hotkey: Ctrl+Alt+B — borderless on active window",
            ["menu.idioma"] = "Language",
            ["boton.enviar"] = "Send",
            ["bandeja.mostrar"] = "Show SinBordes",
            ["bandeja.salir"] = "Quit",
            ["bandeja.globo"] = "Still here in the tray: the watcher handles your library.",
            ["bandeja.restaurada"] = "Window restored.",
            ["bandeja.sinbordes"] = "Window is now borderless.",
            ["pill.sinbordes"] = "borderless",
            ["pill.admin"] = "admin",
            ["fila.apagada"] = "Not running — borderless will apply on launch",
            ["estado.listo"] = "Ready.",
            ["estado.ventanas"] = "{0} windows.",
            ["estado.ventanasBiblio"] = "{0} windows · {1} in library.",
            ["estado.selecciona"] = "Select a window from the list.",
            ["estado.noEjecucion"] = "That game is not running: the watcher will act when it starts.",
            ["estado.restaurada"] = "“{0}” ({1}) restored. If it is in the library, it will re-apply on next launch.",
            ["estado.aplicada"] = "“{0}” ({1}) is now borderless.",
            ["estado.coloresGuardados"] = "Colors saved.",
            ["estado.coloresDefecto"] = "Default colors.",
            ["estado.fueraBiblio"] = "{0} removed from the library.",
            ["estado.enBiblio"] = "{0} added: automatic borderless when detected.",
            ["estado.seleccionaViva"] = "Select a running window.",
            ["estado.altintro"] = "Alt+Enter sent to “{0}”.",
            ["estado.autoarranqueError"] = "Could not update the Windows startup registry entry.",
            ["err.leer"] = "Could not read the window (is the process running as administrator?).",
            ["err.uipi"] = "Windows blocked the change (the process has higher privileges). Run SinBordes as administrator.",
            ["err.monitor"] = "Could not get the window's monitor.",
            ["err.colocar"] = "SetWindowPos failed while positioning the window.",
            ["err.sinEstado"] = "No saved state for that window.",
            ["err.restaurar"] = "SetWindowPos failed while restoring.",
            ["cli.sinVentanas"] = "No visible windows for process “{0}”.",
        },
        ["es"] = new()
        {
            ["boton.aplicar"] = "Hacer borderless",
            ["boton.deshacer"] = "Deshacer",
            ["boton.guardar"] = "Guardar en biblioteca",
            ["boton.quitar"] = "Quitar de biblioteca",
            ["boton.actualizar"] = "Actualizar",
            ["boton.ajustes"] = "Ajustes…",
            ["menu.colores"] = "Colores",
            ["menu.fondo"] = "Fondo…",
            ["menu.panel"] = "Botones y barras…",
            ["menu.acento"] = "Acento…",
            ["menu.texto"] = "Texto…",
            ["menu.restablecer"] = "Restablecer",
            ["menu.esquinas"] = "Esquinas redondeadas",
            ["menu.autoarranque"] = "Arrancar con Windows",
            ["menu.arrancarMin"] = "Arrancar minimizado en bandeja",
            ["menu.cerrarMin"] = "Al cerrar, minimizar a la bandeja",
            ["menu.altintro"] = "Enviar Alt+Intro a la seleccionada",
            ["menu.hotkey"] = "Hotkey: Ctrl+Alt+B — borderless a la ventana activa",
            ["menu.idioma"] = "Idioma",
            ["boton.enviar"] = "Enviar",
            ["bandeja.mostrar"] = "Mostrar SinBordes",
            ["bandeja.salir"] = "Salir",
            ["bandeja.globo"] = "Sigue en la bandeja: el watcher aplica borderless a tu biblioteca.",
            ["bandeja.restaurada"] = "Ventana restaurada.",
            ["bandeja.sinbordes"] = "Ventana sin bordes.",
            ["pill.sinbordes"] = "sin bordes",
            ["pill.admin"] = "admin",
            ["fila.apagada"] = "Sin ejecutar — borderless automático al arrancar",
            ["estado.listo"] = "Listo.",
            ["estado.ventanas"] = "{0} ventanas.",
            ["estado.ventanasBiblio"] = "{0} ventanas · {1} en biblioteca.",
            ["estado.selecciona"] = "Selecciona una ventana de la lista.",
            ["estado.noEjecucion"] = "Ese juego no está en ejecución: el watcher actuará cuando arranque.",
            ["estado.restaurada"] = "«{0}» ({1}) restaurada. Si está en la biblioteca, volverá al relanzar el juego.",
            ["estado.aplicada"] = "«{0}» ({1}) ahora está sin bordes.",
            ["estado.coloresGuardados"] = "Colores guardados.",
            ["estado.coloresDefecto"] = "Colores por defecto.",
            ["estado.fueraBiblio"] = "{0} fuera de la biblioteca.",
            ["estado.enBiblio"] = "{0} en la biblioteca: borderless automático al detectarlo.",
            ["estado.seleccionaViva"] = "Selecciona una ventana en ejecución.",
            ["estado.altintro"] = "Alt+Intro enviado a «{0}».",
            ["estado.autoarranqueError"] = "No se pudo tocar el autoarranque en el registro.",
            ["err.leer"] = "No se pudo leer la ventana (¿el proceso corre como administrador?).",
            ["err.uipi"] = "Windows bloqueó el cambio (el proceso tiene más privilegios). Ejecuta SinBordes como administrador.",
            ["err.monitor"] = "No se pudo obtener el monitor de la ventana.",
            ["err.colocar"] = "SetWindowPos falló al colocar la ventana.",
            ["err.sinEstado"] = "No hay estado guardado de esa ventana.",
            ["err.restaurar"] = "SetWindowPos falló al restaurar.",
            ["cli.sinVentanas"] = "No hay ventanas visibles del proceso «{0}».",
        },
        ["pt"] = new()
        {
            ["boton.aplicar"] = "Deixar sem bordas",
            ["boton.deshacer"] = "Desfazer",
            ["boton.guardar"] = "Adicionar à biblioteca",
            ["boton.quitar"] = "Remover da biblioteca",
            ["boton.actualizar"] = "Atualizar",
            ["boton.ajustes"] = "Configurações…",
            ["menu.colores"] = "Cores",
            ["menu.fondo"] = "Fundo…",
            ["menu.panel"] = "Botões e barras…",
            ["menu.acento"] = "Destaque…",
            ["menu.texto"] = "Texto…",
            ["menu.restablecer"] = "Restaurar padrão",
            ["menu.esquinas"] = "Cantos arredondados",
            ["menu.autoarranque"] = "Iniciar com o Windows",
            ["menu.arrancarMin"] = "Iniciar minimizado na bandeja",
            ["menu.cerrarMin"] = "Fechar minimiza para a bandeja",
            ["menu.altintro"] = "Enviar Alt+Enter à selecionada",
            ["menu.hotkey"] = "Atalho: Ctrl+Alt+B — sem bordas na janela ativa",
            ["menu.idioma"] = "Idioma",
            ["boton.enviar"] = "Enviar",
            ["bandeja.mostrar"] = "Mostrar SinBordes",
            ["bandeja.salir"] = "Sair",
            ["bandeja.globo"] = "Continua na bandeja: o watcher cuida da sua biblioteca.",
            ["bandeja.restaurada"] = "Janela restaurada.",
            ["bandeja.sinbordes"] = "Janela sem bordas.",
            ["pill.sinbordes"] = "sem bordas",
            ["pill.admin"] = "admin",
            ["fila.apagada"] = "Não está em execução — sem bordas automático ao iniciar",
            ["estado.listo"] = "Pronto.",
            ["estado.ventanas"] = "{0} janelas.",
            ["estado.ventanasBiblio"] = "{0} janelas · {1} na biblioteca.",
            ["estado.selecciona"] = "Selecione uma janela da lista.",
            ["estado.noEjecucion"] = "Esse jogo não está em execução: o watcher agirá quando iniciar.",
            ["estado.restaurada"] = "“{0}” ({1}) restaurada. Se estiver na biblioteca, voltará ao reiniciar o jogo.",
            ["estado.aplicada"] = "“{0}” ({1}) agora está sem bordas.",
            ["estado.coloresGuardados"] = "Cores salvas.",
            ["estado.coloresDefecto"] = "Cores padrão.",
            ["estado.fueraBiblio"] = "{0} removido da biblioteca.",
            ["estado.enBiblio"] = "{0} adicionado: sem bordas automático ao detectar.",
            ["estado.seleccionaViva"] = "Selecione uma janela em execução.",
            ["estado.altintro"] = "Alt+Enter enviado a “{0}”.",
            ["estado.autoarranqueError"] = "Não foi possível alterar a inicialização no registro.",
            ["err.leer"] = "Não foi possível ler a janela (o processo roda como administrador?).",
            ["err.uipi"] = "O Windows bloqueou a mudança (o processo tem mais privilégios). Execute o SinBordes como administrador.",
            ["err.monitor"] = "Não foi possível obter o monitor da janela.",
            ["err.colocar"] = "SetWindowPos falhou ao posicionar a janela.",
            ["err.sinEstado"] = "Não há estado salvo dessa janela.",
            ["err.restaurar"] = "SetWindowPos falhou ao restaurar.",
            ["cli.sinVentanas"] = "Nenhuma janela visível do processo “{0}”.",
        },
        ["fr"] = new()
        {
            ["boton.aplicar"] = "Passer sans bordures",
            ["boton.deshacer"] = "Annuler",
            ["boton.guardar"] = "Ajouter à la bibliothèque",
            ["boton.quitar"] = "Retirer de la bibliothèque",
            ["boton.actualizar"] = "Actualiser",
            ["boton.ajustes"] = "Réglages…",
            ["menu.colores"] = "Couleurs",
            ["menu.fondo"] = "Fond…",
            ["menu.panel"] = "Boutons et barres…",
            ["menu.acento"] = "Accent…",
            ["menu.texto"] = "Texte…",
            ["menu.restablecer"] = "Réinitialiser",
            ["menu.esquinas"] = "Coins arrondis",
            ["menu.autoarranque"] = "Lancer avec Windows",
            ["menu.arrancarMin"] = "Démarrer réduit dans la zone de notification",
            ["menu.cerrarMin"] = "Fermer réduit dans la zone de notification",
            ["menu.altintro"] = "Envoyer Alt+Entrée à la sélection",
            ["menu.hotkey"] = "Raccourci : Ctrl+Alt+B — sans bordures sur la fenêtre active",
            ["menu.idioma"] = "Langue",
            ["boton.enviar"] = "Envoyer",
            ["bandeja.mostrar"] = "Afficher SinBordes",
            ["bandeja.salir"] = "Quitter",
            ["bandeja.globo"] = "Toujours là : le watcher s'occupe de votre bibliothèque.",
            ["bandeja.restaurada"] = "Fenêtre restaurée.",
            ["bandeja.sinbordes"] = "Fenêtre sans bordures.",
            ["pill.sinbordes"] = "sans bordures",
            ["pill.admin"] = "admin",
            ["fila.apagada"] = "Pas en cours — sans bordures automatique au lancement",
            ["estado.listo"] = "Prêt.",
            ["estado.ventanas"] = "{0} fenêtres.",
            ["estado.ventanasBiblio"] = "{0} fenêtres · {1} dans la bibliothèque.",
            ["estado.selecciona"] = "Sélectionnez une fenêtre dans la liste.",
            ["estado.noEjecucion"] = "Ce jeu n'est pas lancé : le watcher agira à son démarrage.",
            ["estado.restaurada"] = "« {0} » ({1}) restaurée. Si elle est dans la bibliothèque, cela se réappliquera au relancement.",
            ["estado.aplicada"] = "« {0} » ({1}) est maintenant sans bordures.",
            ["estado.coloresGuardados"] = "Couleurs enregistrées.",
            ["estado.coloresDefecto"] = "Couleurs par défaut.",
            ["estado.fueraBiblio"] = "{0} retiré de la bibliothèque.",
            ["estado.enBiblio"] = "{0} ajouté : sans bordures automatique à la détection.",
            ["estado.seleccionaViva"] = "Sélectionnez une fenêtre en cours d'exécution.",
            ["estado.altintro"] = "Alt+Entrée envoyé à « {0} ».",
            ["estado.autoarranqueError"] = "Impossible de modifier le démarrage automatique dans le registre.",
            ["err.leer"] = "Impossible de lire la fenêtre (le processus tourne-t-il en administrateur ?).",
            ["err.uipi"] = "Windows a bloqué le changement (le processus a plus de privilèges). Lancez SinBordes en administrateur.",
            ["err.monitor"] = "Impossible d'obtenir le moniteur de la fenêtre.",
            ["err.colocar"] = "SetWindowPos a échoué au positionnement.",
            ["err.sinEstado"] = "Aucun état enregistré pour cette fenêtre.",
            ["err.restaurar"] = "SetWindowPos a échoué à la restauration.",
            ["cli.sinVentanas"] = "Aucune fenêtre visible pour le processus « {0} ».",
        },
        ["de"] = new()
        {
            ["boton.aplicar"] = "Randlos machen",
            ["boton.deshacer"] = "Rückgängig",
            ["boton.guardar"] = "Zur Bibliothek hinzufügen",
            ["boton.quitar"] = "Aus Bibliothek entfernen",
            ["boton.actualizar"] = "Aktualisieren",
            ["boton.ajustes"] = "Einstellungen…",
            ["menu.colores"] = "Farben",
            ["menu.fondo"] = "Hintergrund…",
            ["menu.panel"] = "Schaltflächen und Leisten…",
            ["menu.acento"] = "Akzent…",
            ["menu.texto"] = "Text…",
            ["menu.restablecer"] = "Zurücksetzen",
            ["menu.esquinas"] = "Abgerundete Ecken",
            ["menu.autoarranque"] = "Mit Windows starten",
            ["menu.arrancarMin"] = "Minimiert im Infobereich starten",
            ["menu.cerrarMin"] = "Schließen minimiert in den Infobereich",
            ["menu.altintro"] = "Alt+Eingabe an Auswahl senden",
            ["menu.hotkey"] = "Hotkey: Strg+Alt+B — randlos für das aktive Fenster",
            ["menu.idioma"] = "Sprache",
            ["boton.enviar"] = "Senden",
            ["bandeja.mostrar"] = "SinBordes anzeigen",
            ["bandeja.salir"] = "Beenden",
            ["bandeja.globo"] = "Weiter im Infobereich: der Watcher kümmert sich um die Bibliothek.",
            ["bandeja.restaurada"] = "Fenster wiederhergestellt.",
            ["bandeja.sinbordes"] = "Fenster ist jetzt randlos.",
            ["pill.sinbordes"] = "randlos",
            ["pill.admin"] = "Admin",
            ["fila.apagada"] = "Läuft nicht — randlos automatisch beim Start",
            ["estado.listo"] = "Bereit.",
            ["estado.ventanas"] = "{0} Fenster.",
            ["estado.ventanasBiblio"] = "{0} Fenster · {1} in der Bibliothek.",
            ["estado.selecciona"] = "Wähle ein Fenster aus der Liste.",
            ["estado.noEjecucion"] = "Das Spiel läuft nicht: der Watcher handelt beim Start.",
            ["estado.restaurada"] = "„{0}“ ({1}) wiederhergestellt. In der Bibliothek wird es beim Neustart erneut angewendet.",
            ["estado.aplicada"] = "„{0}“ ({1}) ist jetzt randlos.",
            ["estado.coloresGuardados"] = "Farben gespeichert.",
            ["estado.coloresDefecto"] = "Standardfarben.",
            ["estado.fueraBiblio"] = "{0} aus der Bibliothek entfernt.",
            ["estado.enBiblio"] = "{0} hinzugefügt: automatisch randlos bei Erkennung.",
            ["estado.seleccionaViva"] = "Wähle ein laufendes Fenster.",
            ["estado.altintro"] = "Alt+Eingabe an „{0}“ gesendet.",
            ["estado.autoarranqueError"] = "Autostart-Eintrag in der Registry konnte nicht geändert werden.",
            ["err.leer"] = "Fenster konnte nicht gelesen werden (läuft der Prozess als Administrator?).",
            ["err.uipi"] = "Windows hat die Änderung blockiert (der Prozess hat höhere Rechte). SinBordes als Administrator starten.",
            ["err.monitor"] = "Monitor des Fensters konnte nicht ermittelt werden.",
            ["err.colocar"] = "SetWindowPos schlug beim Positionieren fehl.",
            ["err.sinEstado"] = "Kein gespeicherter Zustand für dieses Fenster.",
            ["err.restaurar"] = "SetWindowPos schlug beim Wiederherstellen fehl.",
            ["cli.sinVentanas"] = "Keine sichtbaren Fenster für Prozess „{0}“.",
        },
        ["ru"] = new()
        {
            ["boton.aplicar"] = "Убрать рамки",
            ["boton.deshacer"] = "Отменить",
            ["boton.guardar"] = "В библиотеку",
            ["boton.quitar"] = "Убрать из библиотеки",
            ["boton.actualizar"] = "Обновить",
            ["boton.ajustes"] = "Настройки…",
            ["menu.colores"] = "Цвета",
            ["menu.fondo"] = "Фон…",
            ["menu.panel"] = "Кнопки и панели…",
            ["menu.acento"] = "Акцент…",
            ["menu.texto"] = "Текст…",
            ["menu.restablecer"] = "Сбросить",
            ["menu.esquinas"] = "Скруглённые углы",
            ["menu.autoarranque"] = "Запускать с Windows",
            ["menu.arrancarMin"] = "Запускать свёрнутым в трей",
            ["menu.cerrarMin"] = "Закрытие сворачивает в трей",
            ["menu.altintro"] = "Отправить Alt+Enter выбранному",
            ["menu.hotkey"] = "Горячая клавиша: Ctrl+Alt+B — убрать рамки активного окна",
            ["menu.idioma"] = "Язык",
            ["boton.enviar"] = "Отправить",
            ["bandeja.mostrar"] = "Показать SinBordes",
            ["bandeja.salir"] = "Выход",
            ["bandeja.globo"] = "Программа в трее: watcher следит за вашей библиотекой.",
            ["bandeja.restaurada"] = "Окно восстановлено.",
            ["bandeja.sinbordes"] = "Окно без рамок.",
            ["pill.sinbordes"] = "без рамок",
            ["pill.admin"] = "админ",
            ["fila.apagada"] = "Не запущено — рамки уберутся автоматически при запуске",
            ["estado.listo"] = "Готово.",
            ["estado.ventanas"] = "Окон: {0}.",
            ["estado.ventanasBiblio"] = "Окон: {0} · в библиотеке: {1}.",
            ["estado.selecciona"] = "Выберите окно из списка.",
            ["estado.noEjecucion"] = "Игра не запущена: watcher сработает при запуске.",
            ["estado.restaurada"] = "«{0}» ({1}) восстановлено. Если оно в библиотеке, применится снова при перезапуске.",
            ["estado.aplicada"] = "«{0}» ({1}) теперь без рамок.",
            ["estado.coloresGuardados"] = "Цвета сохранены.",
            ["estado.coloresDefecto"] = "Цвета по умолчанию.",
            ["estado.fueraBiblio"] = "{0} убрано из библиотеки.",
            ["estado.enBiblio"] = "{0} добавлено: рамки уберутся автоматически.",
            ["estado.seleccionaViva"] = "Выберите запущенное окно.",
            ["estado.altintro"] = "Alt+Enter отправлен «{0}».",
            ["estado.autoarranqueError"] = "Не удалось изменить автозапуск в реестре.",
            ["err.leer"] = "Не удалось прочитать окно (процесс запущен от администратора?).",
            ["err.uipi"] = "Windows заблокировал изменение (у процесса больше прав). Запустите SinBordes от администратора.",
            ["err.monitor"] = "Не удалось получить монитор окна.",
            ["err.colocar"] = "SetWindowPos не смог разместить окно.",
            ["err.sinEstado"] = "Нет сохранённого состояния этого окна.",
            ["err.restaurar"] = "SetWindowPos не смог восстановить окно.",
            ["cli.sinVentanas"] = "Нет видимых окон процесса «{0}».",
        },
    };
}
